// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"BattleVoiceMZ","status":true,"description":"[Ver2.2.0]Play voice SE at various situations on battle","parameters":{"ON switch ID":"1","actorCommonSetting":"","volume":"90","pitch":"100","pan":"0","enemyCommonSetting":"","enemyVolume":"90","enemyPitch":"100","enemyPan":"0","Battle Voice Name at Option":"Battle Voice","firstMsgTiming":"0","advanced":"","voiceAtAllDamage":"normal","waitForPlural":"30"}},
{"name":"SVActorPositionMZ","status":true,"description":"[Ver1.1.5]Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"600","actor1 Ypos":"280","actor2 Xpos":"600 + 32","actor2 Ypos":"280 + 48","actor3 Xpos":"600 + 32 * 2","actor3 Ypos":"280 + 48 * 2","actor4 Xpos":"600 + 32 * 3","actor4 Ypos":"280 + 48 * 3"}},
{"name":"StartUpFullScreen","status":false,"description":"Full Screen Startup","parameters":{"Shutdown":"Shutdown","DefaultFullScreen":"false","Immediate":"false","StartUpFullScreen":"Full Screen Startup","UseGameEnd":"true"}}
];
